/*
 *  MoMEMta: a modular implementation of the Matrix Element Method
 *  Copyright (C) 2016  Universite catholique de Louvain (UCL), Belgium
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <momemta/ConfigurationSet.h>
#include <momemta/Module.h>
#include <momemta/Types.h>
#include <momemta/Utils.h>

/** \brief Flat transfer function on |P| (mainly for testing purposes). 
 *
 * This modules implements a constant (=1) transfer function on a particle's \f$|P|\f$.
 *
 * The primary purpose of this module is the validation of the phase-space generator, since it allows
 * computing phase-space volumes and cross-sections by integrating over the reconstructed particle's momenta.
 *
 * The module still takes a 4-momentum as input, since it needs a direction and mass.
 *
 * The range of \f$|P|\f$ values considered is fixed by the `min` and `max` parameters.
 *
 *  - Integration dimension: 1
 *
 *  - Parameters:
 *    - `min` (double): Minimum value for \f$|P|\f$.
 *    - `max` (double): Maximum value for \f$|P|\f$.
 *
 *  - Inputs:
 *    - `ps_point` (double): Phase-space point generated by CUBA.
 *    - `reco_particle` (LorentzVector): Input LorentzVector (experimentally reconstructed particle).
 *
 *  - Outputs:
 *    - `output` (LorentzVector): Output "generated" LorentzVector, only differing from 'reco_particle' by its \f$|P|\f$.
 *    - `TF_times_jacobian` (double): Transfer function (ie, 1) times the jacobian (due to the integration range). 
 */

class FlatTransferFunctionOnP: public Module {
    public:

        FlatTransferFunctionOnP(PoolPtr pool, const ConfigurationSet& parameters): Module(pool, parameters.getModuleName()) {
            m_ps_point = parameters.get<InputTag>("ps_point");
            m_ps_point.resolve(pool);
            
            m_input = parameters.get<InputTag>("reco_particle");
            m_input.resolve(pool);

            m_PMin = parameters.get<double>("min");
            m_PMax = parameters.get<double>("max");
        };

        virtual void work() override {

            const double& ps_point = m_ps_point.get<double>();
            const LorentzVector& reco_particle = m_input.get<LorentzVector>();

            const double range = m_PMax - m_PMin;
            const double gen_P = m_PMin + range*ps_point;

            // To change the particle's |P| without changing its direction and mass:
            double gen_E = sqrt(SQ(gen_P) + SQ(reco_particle.M())); 
            output->SetCoordinates(
                gen_P * std::sin(reco_particle.Theta()) * std::cos(reco_particle.Phi()),
                gen_P * std::sin(reco_particle.Theta()) * std::sin(reco_particle.Phi()),
                gen_P * std::cos(reco_particle.Theta()),
                gen_E);

            // Compute TF*jacobian, ie the jacobian of the transformation of [0,1]->[range_min,range_max]
            *TF_times_jacobian = range;
        }

        virtual size_t dimensions() const override {
            return 1;
        }

    private:

        InputTag m_ps_point;
        InputTag m_input;

        double m_PMin, m_PMax;

        std::shared_ptr<LorentzVector> output = produce<LorentzVector>("output");
        std::shared_ptr<double> TF_times_jacobian = produce<double>("TF_times_jacobian");
};
REGISTER_MODULE(FlatTransferFunctionOnP);
