MoMEMta: lua Namespace Reference
lua Namespace Reference
Utility functions related to lua configuration file parsing.
Detailed Description
Utility functions related to lua configuration file parsing.
The lua configuration file specify a set of modules to execute.
Todo:
describe how the configuration file is parsed and what it structure is
Classes
class invalid_array_error
class invalid_configuration_file
< Thrown if the configuration file is not valid
struct Lazy
Lazy value in lua (delayed evaluation)
struct LazyFunction
Lazy function in lua (delayed function evaluation)
struct LazyTableField
Lazy table field in lua (delayed table access)
class unsupported_type_error
Enumerations
enum Type {
NOT_SUPPORTED, BOOLEAN, STRING, INTEGER,
REAL, INPUT_TAG, PARAMETER_SET
}
List of all supported lua types.
Functions
Type type (lua_State *L, int index)
Extract the type of a lua value.
size_t get_index (lua_State *L, int index)
Convert a negative lua stack index to an absolute index.
int lua_is_array (lua_State *L, int index)
Check if a lua table is an array.
std::pair< boost::any, bool > to_any (lua_State *L, int index)
Convert a lua type to boost::any.
void push_any (lua_State *L, const boost::any &value)
Convert a boost::any to a lua type, and push it to the top of the stack.
template<typename T >
T special_any_cast (const boost::any &value)
template<typename T >
boost::any to_vectorT (lua_State *L, int index)
Convert a lua array to a typed vector, encapsulated into a boost::any.
boost::any to_vector (lua_State *L, int index, Type type)
Convert a lua array to a typed vector, encapsulated into a boost::any.
void setup_hooks (lua_State *L, void *ptr)
Register all C function in the lua userspace.
int module_table_newindex (lua_State *L)
Hook for the metatable __newindex of the module's table.
void register_modules (lua_State *L, void *ptr)
Register modules in lua userspace.
int load_modules (lua_State *L)
Hook for the load_modules lua function. The stack must have one element:
int parameter (lua_State *L)
Hook for the parameter lua function. This function accepts one argument:
std::shared_ptr< lua_State > init_runtime (IOnModuleDeclared *callback)
Initialize the lua runtime.
int generate_cuba_inputtag (lua_State *L)
Define Lua function to generate Cuba phase-space point input-tags.
Type lua_array_unique_type (lua_State *L, int index)
Check if a lua table contains only value from the same type.
template<>
double special_any_cast (const boost::any &value)
Specialization for double type, with implicit conversion from integer.
Enumeration Type Documentation
enum lua::Type
List of all supported lua types.
Enumerator
NOT_SUPPORTED
Type not supported
BOOLEAN
Map to bool
STRING
Map to std::string
INTEGER
Map to int64_t
REAL
Map to double
INPUT_TAG
Map to InputTag
PARAMETER_SET
Map to ParameterSet
Definition at line 35 of file utils.h.
Function Documentation
int lua::generate_cuba_inputtag (lua_State * L)
Define Lua function to generate Cuba phase-space point input-tags.
Parameters
L The current lua state
The Lua function returns an input tag of type cuba::ps_points/i where i gets incremented each time the function is called (starting from 0). This way, the user is sure to always define the correct input tag fothe phase-space points.
Returns
always 1
Definition at line 474 of file utils.cc.
Referenced by setup_hooks(), and to_vectorT().
size_t lua::get_index (lua_State * L, int index)
Convert a negative lua stack index to an absolute index.
Parameters
L The current lua state
index The index to convert
Returns
index if it's positive, otherwise the absolute index obtained by lua_gettop(L) + index + 1
Definition at line 135 of file utils.cc.
Referenced by lua::LazyFunction::LazyFunction(), lua_array_unique_type(), lua_is_array(), ParameterSet::parse(), to_any(), and to_vectorT().
std::shared_ptr< lua_State > lua::init_runtime (IOnModuleDeclared * callback)
Initialize the lua runtime.
Parameters
callback A pointer to an instance of IOnModuleDeclared. This callback is called when a new module is declared in the configuration file.
Returns
A pointer to the global lua state. Once out-of-scope, the pointer will be released using the lua_close function.
Definition at line 460 of file utils.cc.
Referenced by ModuleDeclaredMock::onModuleDeclared(), and to_vectorT().
int lua::load_modules (lua_State * L)
Hook for the load_modules lua function. The stack must have one element:
(string) The filename of the library to load
The library will be loaded, and for each new module, a new global variable will be declared, accessible from the lua configuration
Returns
always 0
Definition at line 411 of file utils.cc.
Referenced by ModuleDeclaredMock::onModuleDeclared(), setup_hooks(), and to_vectorT().
Type lua::lua_array_unique_type (lua_State * L, int index)
Check if a lua table contains only value from the same type.
Returns
-1 if not, or the type of the data in the table
Definition at line 177 of file utils.cc.
Referenced by to_any().
int lua::lua_is_array (lua_State * L, int index)
Check if a lua table is an array.
Returns
-1 if it's not an array, or the size of the array
Check if a lua table is an array
Return -1 if it's not an array, or the size of the array
Definition at line 144 of file utils.cc.
Referenced by to_any(), and type().
int lua::module_table_newindex (lua_State * L)
Hook for the metatable __newindex of the module's table.
This function is called as soon as a new entry is added to a module's table, which means that the user defines a new module from the configuration.
The stack contains 3 elements:
the module type table
the module name (the key in the table)
the module definition (the value associated with the key)
Returns
always 0
Definition at line 343 of file utils.cc.
Referenced by register_modules(), and to_vectorT().
int lua::parameter (lua_State * L)
Hook for the parameter lua function. This function accepts one argument:
(string) The name of the parameter
Internaly, this function creates an anonymous lua function, which returns the value of the parameter from the configuration global table.
Returns
always 1
Definition at line 427 of file utils.cc.
Referenced by setup_hooks(), and to_vectorT().
void lua::push_any (lua_State * L, const boost::any & value)
Convert a boost::any to a lua type, and push it to the top of the stack.
This method does the opposite of lua::to_any: convert a boost::any to the corresponding lua type, and pushing it to the top of the stack.
Parameters
L the current lua state
value The value to convert
Warning
Vectors are currently not supported
Definition at line 285 of file utils.cc.
Referenced by generate_cuba_inputtag(), and lua::LazyTableField::set().
void lua::register_modules (lua_State * L, void * ptr)
Register modules in lua userspace.
For each type of module existing, a global table named as the module's type is declared.
Each entry in this table declare a new module of a given type. The key of the entry is the module's name, and the name of the table is the module's type.
The value is itself a table, defining the configuration of the module
Parameters
L The current lua state
ptr A pointer to an instance of ConfigurationReader
See also
module_table_newindex()
Definition at line 369 of file utils.cc.
Referenced by init_runtime(), load_modules(), and to_vectorT().
void lua::setup_hooks (lua_State * L, void * ptr)
Register all C function in the lua userspace.
Available functions:
load_modules
parameter
Definition at line 444 of file utils.cc.
Referenced by init_runtime(), and to_vectorT().
std::pair< boost::any, bool > lua::to_any (lua_State * L, int index)
Convert a lua type to boost::any.
Returns
A std::pair containing :
a new boost::any encapsulating the lua type and a boolean. If the lua type is not supported, an exception is thrown.
a boolean. If true, it means the encapsulated type is a Lazy value, which must be evaluated later on.
Definition at line 210 of file utils.cc.
Referenced by ParameterSet::Element::Element(), ModuleDeclaredMock::onModuleDeclared(), lua::LazyFunction::operator()(), lua::LazyTableField::operator()(), ParameterSet::parse(), and to_vectorT().
boost::any lua::to_vector (lua_State * L, int index, Type type)
Convert a lua array to a typed vector, encapsulated into a boost::any.
Returns
A new boost::any encapsulating the lua array. If the lua type is not supported, an exception is thrown
Definition at line 308 of file utils.cc.
Referenced by to_any(), and to_vectorT().
template<typename T > boost::any lua::to_vectorT (lua_State * L, int index)
Convert a lua array to a typed vector, encapsulated into a boost::any.
Returns
A new boost::any encapsulating the lua array. If the lua type is not supported, an exception is thrown
Definition at line 165 of file utils.h.
Type lua::type (lua_State * L, int index)
Extract the type of a lua value.
Parameters
L The current lua state
index The index of the value
Returns
The type of the lua value (can be NOT_SUPPORTED if the framework can't handle such value)
Definition at line 100 of file utils.cc.
Referenced by lua_array_unique_type(), register_modules(), to_any(), and to_vectorT().