MoMEMta: InputTag Struct Reference
InputTag Struct Reference
An identifier of a module's output.
#include <InputTag_fwd.h>
Detailed Description
An identifier of a module's output.
An InputTag embed two values:
The name of a module
The name of the output
Optionally, it can also embed an index if the output symbolized by the InputTag is a vector. The InputTag is then an indexed InputTag.
Definition at line 41 of file InputTag_fwd.h.
Public Member Functions
InputTag (const std::string &module, const std::string &parameter)
Construct a new InputTag.
InputTag (const std::string &module, const std::string &parameter, size_t index)
Construct a new indexed InputTag.
InputTag ()=default
Construct an empty InputTag.
bool operator== (const InputTag &rhs) const
Test equality between two InputTags.
std::string toString () const
Convert the InputTag in its string representation.
bool isIndexed () const
void resolve (std::shared_ptr< Pool > pool) const
Link the InputTag to the memory pool.
template<typename T >
const T & get () const
Retrieve from the memory pool the data pointed by the InputTag.
Static Public Member Functions
static bool isInputTag (const std::string &tag)
Check if a given string represent an InputTag.
static InputTag fromString (const std::string &tag)
Create a input tag from its string representation.
Public Attributes
std::string module
The module's name.
std::string parameter
The module's output.
size_t index
The index. Only meaningful if isIndexed() returns true.
Constructor & Destructor Documentation
InputTag::InputTag (const std::string & module, const std::string & parameter)
Construct a new InputTag.
Parameters
module The name of the module
parameter The name of the output
Definition at line 45 of file InputTag.cc.
InputTag::InputTag (const std::string & module, const std::string & parameter, size_t index)
Construct a new indexed InputTag.
Parameters
module The name of the module
parameter The name of the output
index The index inside the collection pointed by the InputTag
Definition at line 50 of file InputTag.cc.
Member Function Documentation
InputTag InputTag::fromString (const std::string & tag) static
Create a input tag from its string representation.
Parameters
tag The string representation of the InputTag
Warning
No check is performed to ensure that the string is an input tag. Use isInputTag() first.
Returns
A new InputTag, as described by tag.
Definition at line 76 of file InputTag.cc.
Referenced by lua::to_any().
template<typename T > const T & InputTag::get () const
Retrieve from the memory pool the data pointed by the InputTag.
Returns
The data pointed by the InputTag
Warning
You must first call once resolve() before calling this function
Definition at line 23 of file InputTag.h.
Referenced by BreitWignerGenerator::work(), Permutator::work(), UniformGenerator::work(), FlatTransferFunctionOnTheta::work(), FlatTransferFunctionOnPhi::work(), FlatTransferFunctionOnP::work(), GaussianTransferFunction::work(), BlockB::work(), BlockF::work(), BlockD::work(), and BinnedTransferFunctionOnEnergy::work().
bool InputTag::isIndexed () const
Returns
True if the InputTag is indexed, false otherwise
Definition at line 94 of file InputTag.cc.
Referenced by get().
bool InputTag::isInputTag (const std::string & tag) static
Check if a given string represent an InputTag.
InputTag are represented as string in the following format:
Module::Parameter[/Index]
Delimiter is :: between the module's name and output, and / between the output and the index.
Warning
Index start at 1, and not at 0 like in C++. We follow here the Lua conventation for indexing.
Parameters
tag The string to test
Returns
True if tag describes an InputTag, false otherwise
Definition at line 55 of file InputTag.cc.
Referenced by lua::to_any(), and lua::type().
bool InputTag::operator== (const InputTag & rhs) const
Test equality between two InputTags.
Two InputTags are equals if their module's name, output and index are the same
Returns
True if the two InputTag are equals, false otherwise
Definition at line 86 of file InputTag.cc.
void InputTag::resolve (std::shared_ptr< Pool > pool) const
Link the InputTag to the memory pool.
Note
You must call this function before calling InputTag::get()
Definition at line 98 of file InputTag.cc.
std::string InputTag::toString () const
Convert the InputTag in its string representation.
Returns
A string representation of the InputTag
Definition at line 90 of file InputTag.cc.
Referenced by Pool::description().
The documentation for this struct was generated from the following files:
include/momemta/impl/InputTag_fwd.h
core/src/InputTag.cc
include/momemta/impl/InputTag.h