MoMEMta: ILuaCallback Class Reference
ILuaCallback Class Reference abstract
Notification callback used for communication between the lua file and MoMEMta.
#include <ILuaCallback.h>
Detailed Description
Notification callback used for communication between the lua file and MoMEMta.
Definition at line 30 of file ILuaCallback.h.
Public Member Functions
virtual void onModuleDeclared (const std::string &type, const std::string &name)=0
A module is declared in the configuration file.
virtual void onIntegrandDeclared (const InputTag &tag)=0
The integrand was defined in the configuration file.
virtual void onNewPath (const ExecutionPath &path)=0
A new path is declared in the configuration file.
virtual void addIntegrationDimension ()=0
A new integration dimension is requested in the configuration file.
virtual void onNewInputDeclared (const std::string &name)=0
The configuration file declared a new input.
Member Function Documentation
addIntegrationDimension()
virtual void ILuaCallback::addIntegrationDimension () pure virtual
A new integration dimension is requested in the configuration file.
This function is called when the user calls the 'add_dimension' lua function
A lua code like
ps_point = add_dimension()
will result in a call to this function
Implemented in LuaCallbackMock, and ConfigurationReader.
Referenced by lua::parameter().
onIntegrandDeclared()
virtual void ILuaCallback::onIntegrandDeclared (const InputTag & tag) pure virtual
The integrand was defined in the configuration file.
This function is called when the user calls the integrand lua function
A lua code like
integrand("module::parameter")
will result in a call to this function with tag equals to module::parameter
Implemented in LuaCallbackMock, and ConfigurationReader.
Referenced by lua::parameter().
onModuleDeclared()
virtual void ILuaCallback::onModuleDeclared (const std::string & type, const std::string & name) pure virtual
A module is declared in the configuration file.
This function is called as soon as a new module is declared in the configuration file.
A lua code like
MatrixElement.module_name = {}
will result in a call to this function with type equals to MatrixElement and name equals to module_name.
Implemented in LuaCallbackMock, and ConfigurationReader.
Referenced by lua::module_table_newindex().
onNewInputDeclared()
virtual void ILuaCallback::onNewInputDeclared (const std::string & name) pure virtual
The configuration file declared a new input.
This function is called when the user calls the declare_input lua function
A lua code like
declare_input("lepton")
will result in a call to this function with name equals to lepton
Implemented in LuaCallbackMock, and ConfigurationReader.
Referenced by lua::declare_input().
onNewPath()
virtual void ILuaCallback::onNewPath (const ExecutionPath & path) pure virtual
A new path is declared in the configuration file.
This function is called when the user declared a new Path instance
A lua code like
p = Path("my", "path")
will result in a call to this function
Implemented in LuaCallbackMock, and ConfigurationReader.
The documentation for this class was generated from the following file:
include/momemta/ILuaCallback.h