MoMEMta: Configuration Class Reference
Configuration Class Reference
A frozen snapshot of the configuration file.
#include <Configuration.h>
Detailed Description
A frozen snapshot of the configuration file.
All the parameters are enforced to be static (ie, all lua::Lazy parameters are evaluated)
Definition at line 36 of file Configuration.h.
Classes
struct ModuleDecl
A module declaration, defined from the configuration file.
Public Member Functions
const std::vector< ModuleDecl > & getModules () const
const ParameterSet & getCubaConfiguration () const
const ParameterSet & getGlobalParameters () const
std::vector< InputTag > getIntegrands () const
std::vector< std::string > getInputs () const
std::vector< std::shared_ptr< ExecutionPath > > getPaths () const
size_t getNDimensions () const
Configuration (const Configuration &)
Copy constructor.
Configuration (const Configuration &&)
Move constructor.
Configuration & operator= (Configuration)
Friends
class ConfigurationReader
Constructor & Destructor Documentation
Configuration()
Configuration::Configuration (const Configuration & other)
Copy constructor.
The current implementation clones the ParameterSet members.
Definition at line 47 of file Configuration.cc.
Referenced by Configuration().
Member Function Documentation
getCubaConfiguration()
const ParameterSet & Configuration::getCubaConfiguration () const
Returns
The cuba configuration as declared in the configuration file
Definition at line 78 of file Configuration.cc.
Referenced by MoMEMta::MoMEMta().
getGlobalParameters()
const ParameterSet & Configuration::getGlobalParameters () const
Returns
The global parameters as declared in the configuration file
Definition at line 82 of file Configuration.cc.
Referenced by MoMEMta::MoMEMta().
getInputs()
std::vector< std::string > Configuration::getInputs () const
Returns
The list of inputs declared in the configuration
Definition at line 98 of file Configuration.cc.
Referenced by getInputs(), and MoMEMta::getIntegrationStatus().
getIntegrands()
std::vector< InputTag > Configuration::getIntegrands () const
Returns
The integrand InputTag as declared in the configuration
Definition at line 86 of file Configuration.cc.
Referenced by getInputs(), and MoMEMta::MoMEMta().
getModules()
const std::vector< Configuration::ModuleDecl > & Configuration::getModules () const
Returns
The list of modules declared from the configuration file
Definition at line 74 of file Configuration.cc.
Referenced by momemta::ComputationGraphBuilder::build(), and MoMEMta::MoMEMta().
getNDimensions()
std::size_t Configuration::getNDimensions () const
Returns
The number of integration dimensions required in the configuration
Definition at line 94 of file Configuration.cc.
Referenced by momemta::ComputationGraphBuilder::build().
getPaths()
std::vector< std::shared_ptr< ExecutionPath > > Configuration::getPaths () const
Returns
The list of Paths as declared in the configuration
Definition at line 90 of file Configuration.cc.
Referenced by momemta::ComputationGraphBuilder::build().
The documentation for this class was generated from the following files:
include/momemta/Configuration.h
core/src/Configuration.cc